services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: peppe:nginx
    volumes:
      - ./project/:/var/www/html/
      - ./docker/nginx/config/:/etc/nginx/conf.d/
      - ./docker/logs/nginx:/var/log/nginx/
    ports:
      - "${NGINX_PORT}:80"
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: peppe:php
    volumes:
      - ./project/:/var/www/html/
      - ./docker/logs/php.log:/var/log/fpm-php.www.log
    ports:
      - "${PHP_PORT}:9000"
  db:
    container_name: ${PROJECT_NAME}_mysql
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    expose:
      - '${MYSQL_PORT}'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql